### ISSUE TITLE
StrMap type

### ISSUE THREAD

**Issue by davidchambers** [plaid/sanctuary-def#29]
It would be a useful to have a StrMap type for values such as `{x: 'X', y: 'Y', z: 'Z'}` and `{x: 1, y: 2, y: 3}`. It would be a unary type, like [`$.Array`][1]. `$.StrMap(a)` would satisfy the requirements of [Functor][2], unlike `$.Object` which does not guarantee a common value type.

[1]: https://github.com/plaid/sanctuary-def#array
[2]: https://github.com/fantasyland/fantasy-land#functor

**Comment by svozza** [comment]
:+1: Nice...

**Comment by davidchambers** [comment]
This turned out to be a lot more difficult than I had imagined. I hope to submit a pull request for discussion this weekend, but it's not going to be pretty. ;)
