### ISSUE TITLE
type classes

### ISSUE THREAD

**Issue by davidchambers** [plaid/sanctuary-def#3]
#1 currently provides `forall a`:

```javascript
//    I :: a -> a
const I = def('I', [a], x => x);
```

But we have no way to constrain a type variable. Consider `concat`:

```javascript
//    concat :: a -> a -> a
const concat = def('concat', [a, a], (x, y) => x.concat(y));
```

We'd like to require that `a` have a [semigroup][1]:

```haskell
concat :: Semigroup a => a -> a -> a
```

We could define a Semigroup pseudotype, to enable:

```javascript
//    concat :: Semigroup -> Semigroup -> Semigroup
const concat = def('concat', [Semigroup, Semigroup], (x, y) => x.concat(y));
```

This loses the constraint that both arguments be of the same type, so nonsensical operations such as `concat([], '')` would be permitted.

Perhaps type constraints could be expressed via a dictionary mapping identifier to type class:

```javascript
const Semigroup = {
  name: 'Semigroup',
  test: x => x != null && typeof x.concat === 'function',
};

//    concat :: Semigroup a => a -> a -> a
const concat = def('concat', {a: Semigroup}, [a, a], (x, y) => x.concat(y));
```

[1]: https://github.com/fantasyland/fantasy-land#semigroup

**Comment by svozza** [comment]
This is a very elegant solution David.
